valor1 = int(input("Digite o primeiro valor: "))
valor2 = int(input("Digite o segundo valor: "))
soma = valor1 + valor2
print(f"A soma entre os valores = {soma}")
subtracao = valor1 - valor2
print(f"A subtracao entre os valores = {subtracao}")
multiplicacao = valor1 * valor2
print(f"A multiplicacao entre os valores = {multiplicacao}")
divisao = valor1 / valor2
print(f"A divisao entre os valores = {divisao}")