algoritmo "Soma"
   var
      valor1, valor2, soma, divisao, subtracao, multiplicacao: real
   inicio
      escreva ("Digite o primeiro valor: ")
      leia (valor1)
      escreva ("Digite o segundo valor: ")
      Leia (valor2)
      soma <- valor1 + valor2
      escreval ("A soma é ", soma)
      subtracao <- valor1 - valor2
      escreval ("A soma é ", subtracao)
      divisao <- valor1 / valor2
      escreval ("A soma é ", divisao)
      multiplicacao <- valor1 * valor2
      escreva ("A soma é ", multiplicacao)
fimalgoritmo
